import { randomUUID } from "node:crypto";
import { type NewRoom, type Room, roomSchema } from "@wolfchatter/shared/schema";
import type { Queryable } from "../db/db.ts";
import { onlyRow } from "../lib/only-row.ts";

interface RoomRow {
  id: string;
  name: string;
  lat: number;
  lng: number;
  created_at: Date;
}

const roomColumns = "id, name, lat, lng, created_at";

/** The database is a boundary like any other, so a row becomes a Room only by passing its schema. */
function toRoom(row: RoomRow): Room {
  return roomSchema.parse({
    id: row.id,
    name: row.name,
    lat: row.lat,
    lng: row.lng,
    createdAt: row.created_at.toISOString(),
  });
}

/** The name is generated by the database from the identity column, never chosen here. */
export async function insertRoom(db: Queryable, point: NewRoom): Promise<Room> {
  const { rows } = await db.query<RoomRow>(
    `INSERT INTO rooms (id, lat, lng) VALUES ($1, $2, $3) RETURNING ${roomColumns}`,
    [randomUUID(), point.lat, point.lng],
  );
  return toRoom(onlyRow(rows));
}

export async function listRooms(db: Queryable): Promise<Room[]> {
  const { rows } = await db.query<RoomRow>(`SELECT ${roomColumns} FROM rooms ORDER BY number`);
  return rows.map(toRoom);
}

export async function roomExists(db: Queryable, roomId: string): Promise<boolean> {
  const { rows } = await db.query("SELECT 1 FROM rooms WHERE id = $1", [roomId]);
  return rows.length === 1;
}
