import type { MapRoom } from "@wolfchatter/shared/client";
import { useState } from "react";

type RoomPanelProps = {
  room: MapRoom | undefined;
  failedToOpen: boolean;
};

/** The name is generated by the database, so there is a moment where there is none to show. */
function PanelHeading({ room, failedToOpen }: RoomPanelProps) {
  if (failedToOpen) {
    return (
      <p role="alert" className="text-accent text-sm">
        That chatroom could not be opened. Try again.
      </p>
    );
  }

  if (room === undefined) {
    return <p className="text-ink/70 text-sm">Click on the map to start a chat</p>;
  }

  if (room.status === "pending") {
    return (
      <h2 className="min-w-0 flex-1" aria-label="Opening the chatroom">
        <span className="block h-5 w-32 animate-pulse rounded bg-ink/10 motion-reduce:animate-none" />
      </h2>
    );
  }

  return <h2 className="min-w-0 flex-1 truncate font-display text-lg">{room.name}</h2>;
}

function SheetToggle({ expanded, onToggle }: { expanded: boolean; onToggle: () => void }) {
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-expanded={expanded}
      aria-label={expanded ? "Collapse the chatroom" : "Expand the chatroom"}
      className="-mr-2 grid size-11 shrink-0 place-items-center text-ink/70 md:hidden"
    >
      <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true">
        <path
          d={expanded ? "M3 10.5 8 5.5l5 5" : "M3 5.5 8 10.5l5-5"}
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
        />
      </svg>
    </button>
  );
}

function MapEmptyState() {
  return (
    <div className="flex flex-col items-center gap-3 py-6 text-center">
      <picture>
        <source srcSet="/brand/state-map-dark.svg" media="(prefers-color-scheme: dark)" />
        <img src="/brand/state-map-light.svg" alt="" className="size-16" />
      </picture>
      <p className="text-ink/70 text-sm">Every click on the map opens a room there.</p>
    </div>
  );
}

/**
 * Below 768 px this is a sheet lying over the map, collapsed to the room's name and pulled
 * up to about two thirds of the height; above it, the right-hand column of the reference.
 * One component either way, because the difference is entirely in the layout — there is no
 * second copy of the panel to keep in step.
 */
export function RoomPanel({ room, failedToOpen }: RoomPanelProps) {
  const [expanded, setExpanded] = useState(false);

  return (
    <section
      aria-label="Chatroom"
      className={`absolute inset-x-0 bottom-0 z-[1000] flex flex-col overflow-hidden rounded-t-2xl
        border-rule border-t bg-ground pb-[env(safe-area-inset-bottom)] transition-[height]
        motion-reduce:transition-none md:static md:h-auto md:w-80 md:rounded-none md:border-t-0
        md:border-l md:pb-0 ${expanded ? "h-[70dvh]" : "h-peek"}`}
    >
      <div className="flex h-peek shrink-0 items-center gap-2 px-4 md:h-auto md:py-4">
        <PanelHeading room={room} failedToOpen={failedToOpen} />
        {room === undefined ? null : (
          <SheetToggle expanded={expanded} onToggle={() => setExpanded(!expanded)} />
        )}
      </div>

      <div className="min-h-0 flex-1 overflow-y-auto px-4 pb-4">
        {room === undefined ? (
          <MapEmptyState />
        ) : (
          <p className="text-ink/70 text-sm">Messages arrive with the next pull request.</p>
        )}
      </div>
    </section>
  );
}
