import type { ChatClient, ChatStore, MapRoom } from "@wolfchatter/shared/client";
import { type KeyboardEvent, type Ref, useEffect, useState } from "react";
import { RoomChat } from "../messages/room-chat.tsx";
import { useRoomMessages } from "../messages/use-chat-store.ts";
import { isSmallViewport } from "./is-small-viewport.ts";

type RoomPanelProps = {
  store: ChatStore;
  client: ChatClient;
  room: MapRoom | undefined;
  failedToOpen: boolean;
  openExpanded: boolean;
  onClose: () => void;
};

type PanelHeadingProps = Pick<RoomPanelProps, "room" | "failedToOpen"> & {
  ref: Ref<HTMLHeadingElement>;
};

/** The name is generated by the database, so there is a moment where there is none to show. */
function PanelHeading({ room, failedToOpen, ref }: PanelHeadingProps) {
  if (failedToOpen) {
    return (
      <p role="alert" className="text-accent-strong text-sm">
        That chatroom could not be opened. Try again.
      </p>
    );
  }

  if (room === undefined) {
    return <p className="text-ink/70 text-sm">Click on the map to start a chat</p>;
  }

  if (room.status === "pending") {
    return (
      <h2 ref={ref} tabIndex={-1} aria-label="Opening the chatroom">
        <span className="block h-5 w-32 animate-pulse rounded bg-ink/10 motion-reduce:animate-none" />
      </h2>
    );
  }

  return (
    <h2 ref={ref} tabIndex={-1} className="truncate font-display text-lg">
      {room.name}
    </h2>
  );
}

function SheetToggle({ expanded, onToggle }: { expanded: boolean; onToggle: () => void }) {
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-expanded={expanded}
      aria-label={expanded ? "Collapse the chatroom" : "Expand the chatroom"}
      className="-mr-2 grid size-11 shrink-0 place-items-center text-ink/70 md:hidden"
    >
      <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true">
        <path
          d={expanded ? "M3 10.5 8 5.5l5 5" : "M3 5.5 8 10.5l5-5"}
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
        />
      </svg>
    </button>
  );
}

function MapEmptyState() {
  return (
    <div className="flex flex-col items-center gap-3 py-6 text-center">
      <picture>
        <source srcSet="/brand/state-map-dark.svg" media="(prefers-color-scheme: dark)" />
        <img src="/brand/state-map-light.svg" alt="" className="size-16" />
      </picture>
      <p className="text-ink/70 text-sm">Every click on the map opens a room there.</p>
    </div>
  );
}

/**
 * Below 768 px this is a sheet lying over the map, collapsed to the room's name and the last
 * thing said in it and pulled up to about two thirds of the height; above it, the right-hand
 * column of the reference. One component either way, because the difference is entirely in
 * the layout — there is no second copy of the panel to keep in step.
 */
export function RoomPanel({ store, client, room, failedToOpen, openExpanded, onClose }: RoomPanelProps) {
  const [expanded, setExpanded] = useState(openExpanded);
  const [heading, setHeading] = useState<HTMLHeadingElement | null>(null);
  const messages = useRoomMessages(store, room?.id);
  const newest = messages.at(-1);
  const roomId = room?.id;

  // The room on show is the only thing that moves the focus here. It is deliberately not the
  // messages: a line arriving while someone is writing would take the keyboard out of the
  // composer, which is the worst thing this panel could do to the person using it.
  useEffect(() => {
    if (roomId === undefined || heading === null) return;

    heading.focus();
  }, [roomId, heading]);

  /** Below 768 px the first Escape puts the sheet down; there is no sheet to put down above it. */
  function dismiss(event: KeyboardEvent<HTMLElement>) {
    if (event.key !== "Escape") return;

    if (expanded && isSmallViewport()) {
      setExpanded(false);
      // The sheet is about to hide whatever holds the focus, and focus inside something
      // invisible is dropped on the floor — the next Escape would then reach nothing.
      event.currentTarget.focus();
      return;
    }

    onClose();
  }

  return (
    <section
      id="chatroom"
      // The skip link lands here, and a section is not focusable on its own.
      tabIndex={-1}
      aria-label="Chatroom"
      data-expanded={expanded}
      onKeyDown={dismiss}
      className={`absolute inset-x-0 bottom-0 z-[1000] flex flex-col overflow-hidden rounded-t-2xl
        border-rule border-t bg-ground pb-[env(safe-area-inset-bottom)] transition-[height]
        motion-reduce:transition-none md:static md:h-auto md:w-80 md:rounded-none md:border-t-0
        md:border-l md:pb-0 ${expanded ? "h-sheet" : "h-peek-safe"}`}
    >
      <div className="flex h-peek shrink-0 items-center gap-2 px-4 md:h-auto md:py-4">
        <div className="min-w-0 flex-1">
          <PanelHeading ref={setHeading} room={room} failedToOpen={failedToOpen} />
          {newest !== undefined && !expanded ? (
            <p className="truncate text-ink/60 text-xs md:hidden">
              <span className="font-display">{newest.username}</span> {newest.body}
            </p>
          ) : null}
        </div>
        {room === undefined ? null : (
          <SheetToggle expanded={expanded} onToggle={() => setExpanded(!expanded)} />
        )}
      </div>

      {/* What the collapsed sheet clips has to be out of reach as well as out of sight, or
          the composer takes focus behind the map. Hidden this way it leaves the tab order and
          the accessibility tree with it, and the breakpoint stays where it belongs, in CSS. */}
      <div className={`flex min-h-0 flex-1 flex-col ${expanded ? "" : "invisible md:visible"}`}>
        {room === undefined ? (
          <div className="min-h-0 flex-1 overflow-y-auto px-4 pb-4">
            <MapEmptyState />
          </div>
        ) : (
          <RoomChat store={store} client={client} room={room} messages={messages} />
        )}
      </div>
    </section>
  );
}
